# Generated by Django 4.1.2 on 2022-11-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
