# Generated by Django 4.1.2 on 2022-11-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='productv2',
        ),
    ]
