# Generated by Django 4.1.2 on 2022-11-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_product_orderproduct_productv2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='productv2',
            new_name='product',
        ),
    ]
