# Generated by Django 4.1.2 on 2022-11-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_orderproduct_order_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='OrderProduct', to='inventory.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='OrderProduct', to='inventory.product'),
            preserve_default=False,
        ),
    ]
