# Generated by Django 4.1.2 on 2022-11-16 23:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_orderproduct_order_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.date(2022, 11, 17)),
        ),
        migrations.CreateModel(
            name='RentProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('renteduntill', models.DateField(default=datetime.date(2022, 11, 24))),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RentProduct', to='inventory.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RentProduct', to='inventory.product')),
            ],
        ),
    ]
