# Generated by Django 4.1.2 on 2022-11-17 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentproduct',
            name='order',
        ),
        migrations.AddField(
            model_name='rentproduct',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RentProduct', to='inventory.profile'),
        ),
    ]
