# Generated by Django 4.1.2 on 2022-11-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_rentproduct_order_rentproduct_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='displayrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='renteduntill',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
