# Generated by Django 4.1.2 on 2022-11-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_rentproduct_renteduntill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
